app/notifications/routes.py
from flask import Blueprint, render_template, session, request
import psycopg2

notifications_bp = Blueprint('notification', __name__)

# Connect to the database
conn = psycopg2.connect(database="volunteers_db", user="postgres",
                        password="arti", host="localhost", port="5432")


def get_notification():
    command = ""
    if session["is_admin"]:
        command = f"SELECT msg FROM notifications " \
                  f"WHERE notification_type = {True} OR user_id = {session['user_id']};"
    else:
        command = f"SELECT msg FROM notifications " \
                  f"WHERE notification_type = {False} AND user_id = {session['user_id']};"

    cursor = conn.cursor()
    cursor.execute(command)
    table_data = cursor.fetchall()
    cursor.close()

    return [notif[0] for notif in table_data]


@notifications_bp.route('/', methods=['GET'])
def notification():
    if session.get('signed_in') is None or session["signed_in"] == False:
        return render_template("index.html")

    return render_template('notification.html', notifications=get_notification(), username=session['username'])


@notifications_bp.route('/delete', methods=['GET', 'POST'])
def notification_delete():
    if request.method == 'POST':
        data = request.get_json()
        notification = data['notification_name'].split('\n')[-2].strip()

        cursor = conn.cursor()
        command = f"DELETE FROM notifications WHERE msg LIKE '%{notification}%';"
        cursor.execute(command)
        cursor.close()
        conn.commit()

        return render_template('notification.html', notifications=get_notification(), username=session['username'])

app/reporting/routes.py
from flask import Blueprint, render_template, session, request, send_file
import psycopg2
from datetime import datetime
from io import BytesIO, StringIO
import csv
from reportlab.lib import colors
from reportlab.lib.pagesizes import letter, landscape
from reportlab.platypus import SimpleDocTemplate, Table, TableStyle, Paragraph
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.lib.units import inch
from reportlab.lib.enums import TA_CENTER

reporting_bp = Blueprint('reporting', __name__)

# Connect to the database
conn = psycopg2.connect(database="volunteers_db", user="postgres",
                        password="arti", host="localhost", port="5432")


@reporting_bp.route('/', methods=['GET'])
def reporting():
    if session.get('signed_in') is None or session["signed_in"] == False:
        return render_template("index.html")

    if not session['is_admin']:
        return render_template('base.html', email=session['email'], username=session['username'],
                               is_admin=session['is_admin'])

    return render_template('generate_report.html', username=session['username'])


@reporting_bp.route('/generate_report', methods=['POST'])
def generate_report():
    if not session.get('is_admin'):
        return render_template("index.html")

    report_type = request.form.get('report_type')
    report_format = request.form.get('report_format')
    start_date = request.form.get('start_date')
    end_date = request.form.get('end_date')

    cur = conn.cursor()

    if report_type == 'volunteer_participation':
        cur.execute("""
            SELECT up.full_name, u.email, u.username, e.event_name, e.event_date
            FROM volunteer_history vh
            JOIN usercredentials u ON vh.user_id = u.id
            JOIN event_details e ON vh.event_id = e.event_id
            JOIN user_profile up ON up.user_id = u.id
            WHERE e.event_date BETWEEN %s AND %s
            ORDER BY e.event_date, u.username
        """, (start_date, end_date))
        data = cur.fetchall()
        data_csv, data_pdf = [], []

        headers = ['Name', 'Email', 'Events Assigned/Participated in']

        volunteers_dict = {}  # email -> [name, [event1, event2]]
        for name, email, username, event_name, event_date in data:
            if email in volunteers_dict:
                if event_name:
                    volunteers_dict[email][1].append(f"{event_name} ({event_date})")
            else:
                if event_name:
                    volunteers_dict[email] = [name, [f"{event_name} ({event_date})"]]
                else:
                    volunteers_dict[email] = [name, ["-"]]

        styles = getSampleStyleSheet()

        for email, val in volunteers_dict.items():
            name, events = val

            formatted_events_pdf = ""
            formatted_events_csv = "["
            for i, event in enumerate(events):
                formatted_events_pdf += event + ("<br /> <br />\n" if i < len(events) - 1 else "")
                formatted_events_csv += event + (", " if i < len(events) - 1 else "")
            formatted_events_csv += "]"

            data_pdf.append([Paragraph(name, styles["Normal"]), Paragraph(email, styles["Normal"]),
                             Paragraph(formatted_events_pdf, styles["Normal"])])
            data_csv.append([name, email, formatted_events_csv])

    elif report_type == 'event_details':
        cur.execute("""
            SELECT e.event_name, e.event_date, e.description, e.location, e.required_skills, e.urgency, up.full_name, uc.email, e.event_id
            FROM event_details e
            LEFT JOIN volunteer_history vh ON e.event_id = vh.event_id
            JOIN user_profile up ON up.user_id = vh.user_id
            JOIN usercredentials uc ON uc.id = vh.user_id
            WHERE e.event_date BETWEEN %s AND %s
            GROUP BY e.event_id, e.event_name, e.event_date, e.location, e.required_skills, e.urgency, up.full_name, uc.email
            ORDER BY e.event_date
        """, (start_date, end_date))
        data = cur.fetchall()
        data_csv, data_pdf = [], []

        headers = ['Event Name', 'Event Date', 'Description', 'Location', 'Required Skills', 'Urgency', 'Volunteers']

        styles = getSampleStyleSheet()

        event_dict = {}  # event_id -> [event_name, event_date, description, location,
        # required_skills, urgency, [volunteer1(email1), volunteer2(email2),...]]
        for details in data:
            event_name, event_date, description = details[0], details[1], details[2]
            location, required_skills, urgency = details[3], details[4], details[5]
            name, email, event_id = details[6], details[7], details[8]

            name_email = f"{name} ({email})"

            if event_id in event_dict:
                event_dict[event_id][-1].append(name_email)
            else:
                event_dict[event_id] = [event_name, event_date, description, location, required_skills,
                                        urgency, [name_email]]

        print(f"eventdict = {event_dict}")
        for event_id, event in event_dict.items():
            volunteers = event[-1]

            formatted_volunteers_pdf = ""
            formatted_volunteers_csv = "["
            for i, volunteer in enumerate(volunteers):
                formatted_volunteers_pdf += volunteer + ("<br /> <br />\n" if i < len(volunteers) - 1 else "")
                formatted_volunteers_csv += volunteer + (", " if i < len(volunteers) - 1 else "")

            formatted_volunteers_csv += "]"

            data_pdf.append([
                Paragraph(event_dict[event_id][0], styles["Normal"]),
                event_dict[event_id][1],
                Paragraph(event_dict[event_id][2], styles["Normal"]),
                Paragraph(event_dict[event_id][3], styles["Normal"]),
                Paragraph(event_dict[event_id][4], styles["Normal"]),
                Paragraph(event_dict[event_id][5], styles["Normal"]),
                Paragraph(formatted_volunteers_pdf, styles["Normal"])
            ])

            data_csv.append([
                event_dict[event_id][0],
                event_dict[event_id][1],
                event_dict[event_id][2],
                event_dict[event_id][3],
                event_dict[event_id][4],
                event_dict[event_id][5],
                formatted_volunteers_csv
            ])

    else:
        cur.close()
        return "Invalid report type", 400

    cur.close()

    report_name = f"{report_type}_{start_date}_to_{end_date}"

    if report_format == 'csv':
        return generate_csv(data_csv, headers, report_name)
    elif report_format == 'pdf':
        return generate_pdf(data_pdf, headers, report_name)
    else:
        return "Invalid report format", 400


def generate_csv(data, headers, report_name):
    si = StringIO()
    cw = csv.writer(si)
    cw.writerow(headers)
    cw.writerows(data)
    output = BytesIO()
    output.write(si.getvalue().encode('utf-8'))
    output.seek(0)
    return send_file(output,
                     mimetype="text/csv",
                     as_attachment=True,
                     download_name=f"{report_name}.csv")


def generate_pdf(data, headers, report_name):
    buffer = BytesIO()
    doc = (SimpleDocTemplate(buffer, pagesize=landscape(letter)))
    elements = []

    styles = getSampleStyleSheet()
    title_style = styles['Heading1']
    title_style.alignment = 1  # Center alignment

    elements.append(Paragraph(f"{report_name.replace('_', ' ').title()} Report", title_style))
    elements.append(Paragraph(f"", styles['Normal']))  # Add some space

    subtitle = f"Report generated on {datetime.now()}."
    elements.append(Paragraph(subtitle, ParagraphStyle(
        name='CenteredHeading4',
        parent=styles['Heading4'],
        alignment=TA_CENTER
    )))

    if 'event_details' in report_name:
        # Adjust column widths for event detail
        col_widths = [1.5 * inch, 1 * inch, 1.5 * inch, 1.8 * inch, 1.8 * inch, 0.8 * inch, 2 * inch]
    else:
        col_widths = [2 * inch, 2.5 * inch, 4 * inch]

    table_data = [headers] + list(data)
    t = Table(table_data, colWidths=col_widths)
    t.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.grey),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.whitesmoke),
        ('ALIGN', (0, 0), (-1, -1), 'CENTER'),
        ('FONTNAME', (0, 0), (-1, 0), 'Helvetica-Bold'),
        ('FONTSIZE', (0, 0), (-1, 0), 12),
        ('BOTTOMPADDING', (0, 0), (-1, 0), 12),
        ('BACKGROUND', (0, 1), (-1, -1), colors.whitesmoke),
        ('GRID', (0, 0), (-1, -1), 1, colors.black),
        ('LINEBELOW', (0, 0), (-1, 0), 1, colors.black),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE')
    ]))
    elements.append(t)
    doc.build(elements)

    buffer.seek(0)
    return send_file(buffer,
                     mimetype="application/pdf",
                     as_attachment=True,
                     download_name=f"{report_name}.pdf")

app/volunteer_history/routes.py
from flask import Blueprint, render_template, session
import psycopg2

history_bp = Blueprint('history', __name__)

# Connect to the database
conn = psycopg2.connect(database="volunteers_db", user="postgres",
                        password="arti", host="localhost", port="5432")


@history_bp.route('/', methods=['GET', 'POST'])
def volunteer_history():
    if session.get('signed_in') is None or session["signed_in"] == False:
        return render_template("index.html")

    return render_template('volunteer_history.html', username=session['username'], user_id=session['user_id'])

app/volunteer_matching/routes.py
from flask import Blueprint, render_template, jsonify, request, session
import psycopg2
from .models import Volunteer, Event

matching_bp = Blueprint('matching', __name__)

# Connect to the database
conn = psycopg2.connect(database="volunteers_db", user="postgres",
                        password="arti", host="localhost", port="5432")

events = []
volunteers = []


@matching_bp.route('/', methods=['GET'])
def volunteer_matching():
    if session.get('signed_in') is None or session["signed_in"] == False:
        return render_template("index.html")

    if not session['is_admin']:
        return render_template('base.html', email=session['email'], username=session['username'],
                               is_admin=session['is_admin'])

    # get_volunteers()
    # get_events()
    # get_events()
    return render_template('volunteer_matching.html', username=session['username'])


@matching_bp.route('/api/volunteers', methods=['GET', 'POST'])
def get_volunteers():
    global volunteers
    if len(volunteers) > 0:
        volunteers = []

    data = request.get_json()

    cursor = conn.cursor()
    user_id = data.get('user_id')

    if session['is_admin'] or user_id == -1:
        command = f"SELECT * FROM user_profile;"
    else:
        command = f"SELECT * FROM user_profile WHERE user_id = {data['user_id']};"

    cursor.execute(command)
    table_data = cursor.fetchall()

    # create Volunteer objects and store in volunteer list
    for row in table_data:
        # fetch this user's email
        command = f"SELECT email FROM usercredentials WHERE id = {row[0]};"
        cursor.execute(command)
        email = cursor.fetchone()[0]

        # Fetch volunteer's history.
        command = f"SELECT event_id FROM volunteer_history WHERE user_id = {row[0]};"
        cursor.execute(command)
        history = []
        table_data = cursor.fetchall()

        for hist in table_data:
            history.append({"event_id": hist[0], "status": "Incomplete"})
        # End volunteer history

        formatted_skills = row[7].split(',')
        volunteer = Volunteer(
            user_id=row[0],
            name=row[1],
            address1=row[2],
            address2=row[3],
            city=row[4],
            state=row[5],
            zip=row[6],
            skills=formatted_skills,
            preferences=row[8],
            availability=[row[9]],
            email=email,
            # phone="(123)-456-7890",
            history=history
        )
        volunteers.append(volunteer)

    cursor.close()

    return jsonify([volunteer.to_dict() for volunteer in volunteers])


@matching_bp.route('/api/events', methods=['GET'])
def get_events():
    global events
    if len(events) > 0:
        events = []

    cursor = conn.cursor()

    command = f"SELECT * FROM event_details;"

    cursor.execute(command)
    table_data = cursor.fetchall()
    cursor.close()

    # create Event objects and store in event list
    for row in table_data:
        formatted_required_skills = row[4].split(",")
        event = Event(
            name=row[1],
            description=row[2],
            location=row[3],
            required_skills=formatted_required_skills,
            urgency=row[5],
            date=row[6],
            id=row[0],
        )
        events.append(event)

    return jsonify([event.to_dict() for event in events])


@matching_bp.route('/api/assign_event', methods=['POST'])
def assign_event():
    data = request.get_json()
    user_id = data.get('user_id')
    volunteer_name = data.get('volunteer_name')
    event_name = data.get('event_name')

    get_volunteers()
    get_events()

    for volunteer in volunteers:
        # if volunteer.name == volunteer_name:
        if volunteer.user_id == user_id:
            volunteer.assigned_event = event_name
            cursor = conn.cursor()
            # command = f'''SELECT user_id FROM user_profile WHERE full_name = '{volunteer_name}';'''
            # cursor.execute(command)
            # user_id = cursor.fetchone()[0]

            command = f'''SELECT event_id, event_date FROM event_details WHERE event_name = '{event_name}';'''
            cursor.execute(command)
            table_data = cursor.fetchone()
            event_id = table_data[0]
            event_date = table_data[1]

            command = f'''SELECT * from volunteer_history WHERE user_id = {user_id} AND event_id = {event_id};'''
            cursor.execute(command)
            table_data = cursor.fetchone()
            if table_data:
                return jsonify({
                                   "message": f"Event '{event_name}' HAS ALREADY BEEN assigned to volunteer '{volunteer_name}'."}), 200

            command = f'''INSERT INTO volunteer_history(user_id, event_id) VALUES ('{user_id}', '{event_id}');'''
            cursor.execute(command)

            command = (f"INSERT INTO notifications (user_id, msg, notification_type) "
                       f"VALUES ({user_id}, 'You have been assigned the event {event_name} on {event_date}', {False});")
            cursor.execute(command)

            cursor.close()
            conn.commit()
            return jsonify({"message": f"Event '{event_name}' assigned to volunteer '{volunteer_name}'"}), 200

    return jsonify({"error": "Volunteer not found"}), 404

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== REMIXICONS ===============-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="../static/css/styles.css">

    <title>Dashboard - We Love Volunteering</title>
</head>
<body>
<div class="container">
    <div class="header">
        <h2>Welcome, <span id="username" style="color:#44958f;">{{ username }}</span>!</h2>
        <div class="header-icons">
            <a href="/profile" class="icon-link">Profile <i class="ri-user-line"></i></a>
            <a href="/notifications" class="icon-link">Notification <i class="ri-notification-line"></i></a>
            <a href="/logout" class="icon-link">Logout <i class="ri-logout-box-line"></i></a>

        </div>
    </div>
    <div class="content">
        <div class="button-column">
            <div class="button-container">
                {% if is_admin %}
                    <a href="/events" class="dashboard-button">Event Management Form</a>
                    <a href="/matching" class="dashboard-button">Volunteer Matching Form</a>
                    <a href="/reporting" class="dashboard-button" style="width: 250px;">Generate Report</a>
                {% endif %}
                <a href="/history" class="dashboard-button" style="width: 250px;">Volunteer History</a>
            </div>
        </div>
        <div class="image-column">
            <img src="../static/img/—Pngtree—learn to raise hands gesture_4729678.png" alt="Dashboard Image"
                 class="dashboard-img">
        </div>
    </div>
    <footer class="footer">
        &copy; 2024 We Love Volunteering. All rights reserved.
    </footer>
</div>

<!--=============== MAIN JS ===============-->
<script src="../static/js/main.js"></script>
</body>
</html>

templates/display.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== REMIXICONS ===============-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="../static/css/styles.css">

    <title>Event Details</title>
</head>

<body>

    <div class="container">
        <div class="header">
            <h2>Welcome, <span id="username" style="color:#44958f;">{{ username }}</span>!</h2>
            <div class="header-icons">
                <a href="/base" class="icon-link">Dashboard<i class="ri-dashboard-line"></i></a>
                <a href="/profile" class="icon-link">Profile<i class="ri-user-line"></i></a>
                <a href="/notifications" class="icon-link">Notification <i class="ri-notification-line"></i></a>
                <a href="/logout" class="icon-link">Logout<i class="ri-logout-box-line"></i></a>
            </div>
        </div>
        <div class="login__content">
            <div class="title-container">
                <h1 class="main-title"><span>I</span><br><span>LOVE</span><br><span>VOLUNTEERING</span></h1>
            </div>
            <div class="event_details">
                <h2>Event Details</h2>

                <table class="display_table">
                  <tr>
                    <td class="event__label"><strong>Event Name</strong></td>
                    <td><span id="eventName">{{ event_name }}</span></td>
                  </tr>
                  <tr>
                    <td><strong>Event Description</strong></td>
                    <td><span id="eventDescription">{{ event_description }}</span></td>
                  </tr>
                  <tr>
                    <td><strong>Location</strong></td>
                    <td><span id="location"></span>{{ event_location }}</td>
                  </tr>
                  <tr>
                    <td><strong>Required Skills</strong></td>
                    <td><span id="requiredSkills">{{ required_skills | join(', ') }}</span></td>
                  </tr>
                  <tr>
                    <td><strong>Urgency</strong></td>
                    <td><span id="urgency">{{ urgency }}</span></td>
                  </tr>
                  <tr>
                    <td><strong>Event Date</strong></td>
                    <td><span id="eventDate">{{ event_date }}</span></td>
                  </tr>
                </table>
            </div>
        </div>
    </div>
</body>
</html>

templates/forgot.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== REMIXICONS ===============-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="../static/css/styles.css">

    <title>Forgot Password - We Love Volunteering</title>
</head>
<body>
<!--    <div class="theme-toggle">-->
<!--        <label class="switch">-->
<!--            <input type="checkbox" id="theme-switch">-->
<!--            <span class="slider round"></span>-->
<!--        </label>-->
<!--        <span id="theme-label">Dark Mode</span>-->
<!--    </div>-->
    <div class="container">
        <div class="login__content">
            <div class="title-container">
                <h1 class="main-title"><span>I</span><br><span>LOVE</span><br><span>VOLUNTEERING</span></h1>
            </div>
            <div class="image-container">
                <img src="../static/img/vol7.png" alt="forgot password image" class="login__img">
                <form action="/" method="POST" class="login__form" id="forgot-form">
                    <div>
                        <h1 class="login__title">Forgot Password</h1>
                        <p class="login__description">Enter your email to reset your password.</p>
                    </div>
                    <div>
                        <div class="login__inputs">
                            <div>
                                <label for="input-email" class="login__label">Email</label>
                                <input type="email" placeholder="Enter your email address" required class="login__input" id="input-email">
                            </div>
                        </div>
                    </div>
                    <div>
                        <div class="login__buttons">
                            <button type="submit" class="login__button">Submit</button>
                            <a href="\" class="login__button login__button-ghost">Back to Login</a>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>

    <!--=============== MAIN JS ===============-->
    <script src="../static/js/main.js"></script>
    <script>
        document.getElementById('forgot-form').addEventListener('submit', async function(event) {
            event.preventDefault();
            const email = document.getElementById('input-email').value;

            const response = await fetch('/forgot', {
                method: 'POST',
                headers: {
                    'Content-Type': 'application/json',
                },
                body: JSON.stringify({ email }),
            });

            if (response.ok) {
                alert('Password reset link sent to your email');
                window.location.href = '/';
            } else {
                const data = await response.json();
                alert(data.message);
            }
        });
    </script>
</body>
</html>

templates/generate_report.html
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== REMIXICONS ===============-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="../static/css/styles.css">

    <title>Dashboard - We Love Volunteering</title>
</head>
<div class="container">
    <div class="header">
        <h2>Welcome, <span id="username" style="color:#44958f;">{{ username }}</span>!</h2>
        <div class="header-icons">
            <a href="/base" class="icon-link">Dashboard<i class="ri-dashboard-line"></i></a>
            <a href="/profile" class="icon-link">Profile <i class="ri-user-line"></i></a>
            <a href="/notifications" class="icon-link">Notification <i class="ri-notification-line"></i></a>
            <a href="/logout" class="icon-link">Logout <i class="ri-logout-box-line"></i></a>
        </div>
    </div>
    
    <div class="content">
        <div class="title-container">
            <h1 class="main-title">Generate <span>Report</span></h1>
        </div>
        <div class="event__form" style="right: 400px;top: 160px;width: 550px;">
            <form action="{{ url_for('reporting.generate_report') }}" method="post" id="reportForm">
                <div class="form-group">
                    <label for="report_type" class="login__label">Report Type:</label>
                    <select name="report_type" id="report_type" class="login__input" required>
                        <option value="">Select a report type</option>
                        <option value="volunteer_participation">Volunteers and Participation History</option>
                        <option value="event_details">Event Details and Volunteer Assignments</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="report_format" class="login__label">Report Format:</label>
                    <select name="report_format" id="report_format" class="login__input" required>
                        <option value="">Select a format</option>
                        <option value="pdf">PDF</option>
                        <option value="csv">CSV</option>
                    </select>
                </div>
                <div class="form-group">
                    <label for="start_date" class="login__label">Start Date:</label>
                    <input type="date" name="start_date" id="start_date" class="login__input" required>
                </div>
                <div class="form-group">
                    <label for="end_date" class="login__label">End Date:</label>
                    <input type="date" name="end_date" id="end_date" class="login__input" required>
                </div>
                <br/>
                <button type="submit" class="login__button" style="width: 95%;">Generate Report</button>
            </form>
        </div>
    </div>

    <footer class="footer">
        &copy; 2024 We Love Volunteering. All rights reserved.
    </footer>
</div>

<script>
    document.addEventListener('DOMContentLoaded', function() {
        const form = document.getElementById('reportForm');
        form.addEventListener('submit', function(event) {
            event.preventDefault();
            const formData = new FormData(form);
            const reportType = formData.get('report_type');
            const reportFormat = formData.get('report_format');
            const startDate = formData.get('start_date');
            const endDate = formData.get('end_date');
            const reportName = `${reportType}_${startDate}_to_${endDate}.${reportFormat}`;
            
            fetch("{{ url_for('reporting.generate_report') }}", {
                method: 'POST',
                body: formData
            })
            .then(function(response) {
                if (response.ok) {
                    return response.blob();
                }
                throw new Error('Network response was not ok.');
            })
            .then(function(blob) {
                const url = window.URL.createObjectURL(blob);
                const a = document.createElement('a');
                a.style.display = 'none';
                a.href = url;
                a.download = reportName;
                document.body.appendChild(a);
                a.click();
                window.URL.revokeObjectURL(url);
            })
            .catch(function(error) {
                console.error('Error:', error);
                alert('An error occurred while generating the report. Please try again.');
            });
        });
    });
</script>

templates/volunteer_matching.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <!--=============== REMIXICONS ===============-->
    <link href="https://cdn.jsdelivr.net/npm/remixicon@2.5.0/fonts/remixicon.css" rel="stylesheet">

    <!--=============== CSS ===============-->
    <link rel="stylesheet" href="../static/css/styles.css">
    <link rel="stylesheet" href="../static/css/volunteer.css">

    <title>Volunteer Matching</title>
</head>
<body>
    <div class="container">
        <div class="header">
            <h2>Welcome, <span id="username" style="color:#44958f;">{{ username }}</span>!</h2>
            <div class="header-icons">
                <a href="/base" class="icon-link">Dashboard<i class="ri-dashboard-line"></i></a>
                <a href="/profile" class="icon-link">Profile<i class="ri-user-line"></i></a>
                <a href="/notifications" class="icon-link">Notification <i class="ri-notification-line"></i></a>
                <a href="/logout" class="icon-link">Logout<i class="ri-logout-box-line"></i></a>
            </div>
        </div>
        <div class="content">
            <div class="matching-form-container">
                <div class="volunteer-section">
                    <div class="volunteer-list">
                        <h2 class="volunteer-list-title">Volunteer List</h2>
                        <ul id="volunteer-list" class="list"></ul>
                    </div>
                    <div class="volunteer-info" id="volunteer-info">
                        <h2 class="volunteer-info-title">Volunteer Info</h2>
                        <div id="info-content" class="info-content"></div>
                    </div>
                </div>
    
                <div class="event-section">
                    <div class="event-info" id="event-info">
                        <h2 class="event-info-title">Event List</h2>
                        <ul id="event-list" class="list"></ul>
                    </div>
                    <div class="eventInformation" id="event-information">
                        <h2 class="event-info-title">Event Info</h2>
                        <ul id="event-content" class="info-content"></ul>
                    </div>
                </div>
    
                <div class="button-container">
                    <button class="info-button" onclick="assignEvent()">Assign Event</button>
                </div>
            </div>
        </div>
    </div>

    <script src="../static/js/volunteerlist.js"></script>
</body>
</html>